services:
  Danilovl\ParameterBundle\Service\ParameterService:
    public: true
    autowire: true

  Danilovl\ParameterBundle\Interfaces\ParameterServiceInterface: '@Danilovl\ParameterBundle\Service\ParameterService'
