services:
  danilovl.get_parameter:
    class: Danilovl\GetParameterBundle\Services\GetParameterService
    public: true
    arguments:
      - '@service_container'

  Danilovl\GetParameterBundle\Services\GetParameterService: '@danilovl.get_parameter'