services:
  _defaults:
    public: true

  danilovl.parameter:
    class: Danilovl\ParameterBundle\Services\ParameterService
    arguments:
      - '@parameter_bag'

  Danilovl\ParameterBundle\Interfaces\ParameterServiceInterface: '@danilovl.parameter'
