services:
  danilovl.parameter:
    class: Danilovl\ParameterBundle\Services\ParameterService
    public: true
    arguments:
      - '@parameter_bag'

  Danilovl\ParameterBundle\Services\ParameterService: '@danilovl.parameter'
