services:
  danilovl.twig.parameter:
    class: Danilovl\ParameterBundle\Twig\ParameterExtension
    public: false
    arguments:
      - '@danilovl.parameter'
    tags:
      - { name: twig.extension }
